import tkinter as tk

mainwindow=tk.Tk()
mainwindow.title('' )
mainwindow.geometry('1200x800+360+120')
mainwindow.config(bg='#ccddff')

lab_mainwindow_title=tk.Label(mainwindow,text='menu',bg='#ccddff',font=('標楷體',30))
lab_mainwindow_title.place(x=540,y=0)

lab_1st=tk.Label(mainwindow,text='first',bg='#ccddff',font=('標楷體',20))
lab_1st.place(x=100,y=100)
lab_2nd=tk.Label(mainwindow,text='second',bg='#ccddff',font=('標楷體',20))
lab_2nd.place(x=400,y=100)
lab_3rd=tk.Label(mainwindow,text='third',bg='#ccddff',font=('標楷體',20))
lab_3rd.place(x=725,y=100)
lab_4th=tk.Label(mainwindow,text='fourth',bg='#ccddff',font=('標楷體',20))
lab_4th.place(x=1010,y=100)

lab_1st_cup=tk.Label(mainwindow,text='drink',bg='#ccddff',font=('標楷體',15))
lab_1st_cup.place(x=80,y=200)
lab_1st_sause=tk.Label(mainwindow,text='sause',bg='#ccddff',font=('標楷體',15))
lab_1st_sause.place(x=160,y=200)
lab_2nd_cup=tk.Label(mainwindow,text='drink',bg='#ccddff',font=('標楷體',15))
lab_2nd_cup.place(x=382,y=200)
lab_2nd_sause=tk.Label(mainwindow,text='sause',bg='#ccddff',font=('標楷體',15))
lab_2nd_sause.place(x=462,y=200)
lab_3rd_cup=tk.Label(mainwindow,text='drink',bg='#ccddff',font=('標楷體',15))
lab_3rd_cup.place(x=707,y=200)
lab_3rd_sause=tk.Label(mainwindow,text='sause',bg='#ccddff',font=('標楷體',15))
lab_3rd_sause.place(x=787,y=200)
lab_4th_cup=tk.Label(mainwindow,text='drink',bg='#ccddff',font=('標楷體',15))
lab_4th_cup.place(x=993,y=200)
lab_4th_sause=tk.Label(mainwindow,text='sause',bg='#ccddff',font=('標楷體',15))
lab_4th_sause.place(x=1073,y=200)

order=[[0,0],
       [0,0],
       [0,0],
       [0,0]]
finish_order=[[0,0],
              [0,0],
              [0,0],
              [0,0]]
get_order=[[0,0],
       [0,0],
       [0,0],
       [0,0]]
for i in range(0,4):
    for j in range(0,2):
        get_order[i][j]=tk.IntVar()

en_1st_cup=tk.Entry(mainwindow,textvariable=get_order[0][0],width=5)
en_1st_cup.place(x=80,y=300)
# en_1st_sause=tk.Entry(mainwindow,textvariable=get_order[0][1],width=5)
# en_1st_sause.place(x=160,y=300)
en_2nd_cup=tk.Entry(mainwindow,textvariable=get_order[1][0],width=5)
en_2nd_cup.place(x=382,y=300)
# en_2nd_sause=tk.Entry(mainwindow,textvariable=get_order[1][1],width=5)
# en_2nd_sause.place(x=462,y=300)
en_3rd_cup=tk.Entry(mainwindow,textvariable=get_order[2][0],width=5)
en_3rd_cup.place(x=707,y=300)
# en_3rd_sause=tk.Entry(mainwindow,textvariable=get_order[2][1],width=5)
# en_3rd_sause.place(x=787,y=300)
en_4th_cup=tk.Entry(mainwindow,textvariable=get_order[3][0],width=5)
en_4th_cup.place(x=993,y=300)
# en_4th_sause=tk.Entry(mainwindow,textvariable=get_order[3][1],width=5)
# en_4th_sause.place(x=1073,y=300)

def print_order():
    mainwindow.destroy()
    for i in range(0,4):
        for j in range(0,2):
            order[i][j]=get_order[i][j].get()
            if j==0:
                print( '第%d筆訂單飲料:%d個'%(i+1,order[i][j]))
            elif j==1: 
                order[i][j]=3-get_order[i][0].get()
                print( '第%d筆訂單醬料:%d個'%(i+1,order[i][j]))

btnExit=tk.Button(mainwindow,text="exit",bg='red',command=mainwindow.destroy)
btnExit.place(x=1147,y=0)
btn_order=tk.Button(mainwindow,text='send order',bg='yellow',font=('標楷體',40), command=print_order)
btn_order.place(x=850,y=700)


# 點餐界面
# pretestwindow=tk.Tk()
# pretestwindow.title('premain')
# pretestwindow.geometry('1200x800+360+120')
# pretestwindow.config(bg='#ddccff')
cupx=tk.DoubleVar()
cupx.set(0.00)
cupy=tk.DoubleVar()
cupy.set(0.00)
cupz=tk.DoubleVar()
cupz.set(0.00)
cupworkx=tk.DoubleVar()
cupworkx.set(0.00)
cupworky=tk.DoubleVar()
cupworky.set(0.00)
cupworkz=tk.DoubleVar()
cupworkz.set(0.00)
cuplidx=tk.DoubleVar()
cuplidx.set(0.00)
cuplidy=tk.DoubleVar()
cuplidy.set(0.00)
cuplidz=tk.DoubleVar()
cuplidz.set(0.00)
cuplidworkx=tk.DoubleVar()
cuplidworkx.set(0.00)
cuplidworky=tk.DoubleVar()
cuplidworky.set(0.00)
cuplidworkz=tk.DoubleVar()
cuplidworkz.set(0.00)
sausex=tk.DoubleVar()
sausex.set(0.00)
sausey=tk.DoubleVar()
sausey.set(0.00)
sausez=tk.DoubleVar()
sausez.set(0.00)
sauseworkx=tk.DoubleVar()
sauseworkx.set(0.00)
sauseworky=tk.DoubleVar()
sauseworky.set(0.00)
sauseworkz=tk.DoubleVar()
sauseworkz.set(0.00)
sauselidworkx=tk.DoubleVar()
sauselidworkx.set(0.00)
sauselidworky=tk.DoubleVar()
sauselidworky.set(0.00)
sauselidworkz=tk.DoubleVar()
sauselidworkz.set(0.00)
sauselidx=tk.DoubleVar()
sauselidx.set(0.00)
sauselidy=tk.DoubleVar()
sauselidy.set(0.00)
sauselidz=tk.DoubleVar()
sauselidz.set(0.00)
test = tk.IntVar()
test.set(1000)
# print(cupx.get(),type(cupx.get()))

def precup():
    # global cupx

    def pls(num):
        num.set(num.get()+0.5)
        print(num.get())
    def mns(num):
        num.set(num.get()-0.5)
        print(num.get())
    pretestwindow_cup=tk.Toplevel(mainwindow)
    pretestwindow_cup.title('precup' )
    pretestwindow_cup.geometry('900x600+360+120')
    pretestwindow_cup.config(bg='#ddccff')
    btnExit=tk.Button(pretestwindow_cup,text="exit",bg='red',command=pretestwindow_cup.destroy)
    btnExit.place(x=847,y=0)
    plsx=tk.Button(pretestwindow_cup,text="+",bg='#ddccff',command=lambda:pls(cupx))
    plsx.place(x=100,y=0)
    lab_cupx=tk.Label(pretestwindow_cup,textvariable=cupx,padx=20)
    lab_cupx.place(x=150,y=0)
    mnsx=tk.Button(pretestwindow_cup,text="-",bg='#ddccff',command=lambda:mns(cupx))
    mnsx.place(x=200,y=0)
    plsy=tk.Button(pretestwindow_cup,text="+",bg='#ddccff',command=lambda:pls(cupy))
    plsy.place(x=100,y=50)
    lab_cupy=tk.Label(pretestwindow_cup,textvariable=cupy,padx=20)
    lab_cupy.place(x=150,y=50)
    mnsy=tk.Button(pretestwindow_cup,text="-",bg='#ddccff',command=lambda:mns(cupy))
    mnsy.place(x=200,y=50)
    plsz=tk.Button(pretestwindow_cup,text="+",bg='#ddccff',command=lambda:pls(cupz))
    plsz.place(x=100,y=100)
    lab_cupz=tk.Label(pretestwindow_cup,textvariable=cupz,padx=20)
    lab_cupz.place(x=150,y=100)
    mnsz=tk.Button(pretestwindow_cup,text="-",bg='#ddccff',command=lambda:mns(cupz))
    mnsz.place(x=200,y=100)

    workplsx=tk.Button(pretestwindow_cup,text="+",bg='#ddccff',command=lambda:pls(cupworkx))
    workplsx.place(x=500,y=0)
    worklab_cupx=tk.Label(pretestwindow_cup,textvariable=cupworkx,padx=20)
    worklab_cupx.place(x=550,y=0)
    workmnsx=tk.Button(pretestwindow_cup,text="-",bg='#ddccff',command=lambda:mns(cupworkx))
    workmnsx.place(x=600,y=0)
    workplsy=tk.Button(pretestwindow_cup,text="+",bg='#ddccff',command=lambda:pls(cupworky))
    workplsy.place(x=500,y=50)
    worklab_cupy=tk.Label(pretestwindow_cup,textvariable=cupworky,padx=20)
    worklab_cupy.place(x=550,y=50)
    workmnsy=tk.Button(pretestwindow_cup,text="-",bg='#ddccff',command=lambda:mns(cupworky))
    workmnsy.place(x=600,y=50)
    workplsz=tk.Button(pretestwindow_cup,text="+",bg='#ddccff',command=lambda:pls(cupworkz))
    workplsz.place(x=500,y=100)
    worklab_cupz=tk.Label(pretestwindow_cup,textvariable=cupworkz,padx=20)
    worklab_cupz.place(x=550,y=100)
    workmnsz=tk.Button(pretestwindow_cup,text="-",bg='#ddccff',command=lambda:mns(cupworkz))
    workmnsz.place(x=600,y=100)


def precuplid():
    def pls(num):
        num.set(num.get()+0.5)
        print(num.get())
    def mns(num):
        num.set(num.get()-0.5)
        print(num.get())
    pretestwindow_cuplid=tk.Toplevel(mainwindow)
    pretestwindow_cuplid.title('precuplid' )
    pretestwindow_cuplid.geometry('900x600+360+120')
    pretestwindow_cuplid.config(bg='#ddccff')
    btnExit=tk.Button(pretestwindow_cuplid,text="exit",bg='red',command=pretestwindow_cuplid.destroy)
    btnExit.place(x=847,y=0)
    plsx=tk.Button(pretestwindow_cuplid,text="+",bg='#ddccff',command=lambda:pls(cuplidx))
    plsx.place(x=100,y=0)
    lab_cuplidx=tk.Label(pretestwindow_cuplid,textvariable=cuplidx,padx=20)
    lab_cuplidx.place(x=150,y=0)
    mnsx=tk.Button(pretestwindow_cuplid,text="-",bg='#ddccff',command=lambda:mns(cuplidx))
    mnsx.place(x=200,y=0)
    plsy=tk.Button(pretestwindow_cuplid,text="+",bg='#ddccff',command=lambda:pls(cuplidy))
    plsy.place(x=100,y=50)
    lab_cuplidy=tk.Label(pretestwindow_cuplid,textvariable=cuplidy,padx=20)
    lab_cuplidy.place(x=150,y=50)
    mnsy=tk.Button(pretestwindow_cuplid,text="-",bg='#ddccff',command=lambda:mns(cuplidy))
    mnsy.place(x=200,y=50)
    plsz=tk.Button(pretestwindow_cuplid,text="+",bg='#ddccff',command=lambda:pls(cuplidz))
    plsz.place(x=100,y=100)
    lab_cuplidz=tk.Label(pretestwindow_cuplid,textvariable=cuplidz,padx=20)
    lab_cuplidz.place(x=150,y=100)
    mnsz=tk.Button(pretestwindow_cuplid,text="-",bg='#ddccff',command=lambda:mns(cuplidz))
    mnsz.place(x=200,y=100)

    workplsx=tk.Button(pretestwindow_cuplid,text="+",bg='#ddccff',command=lambda:pls(cuplidworkx))
    workplsx.place(x=500,y=0)
    worklab_cuplidx=tk.Label(pretestwindow_cuplid,textvariable=cuplidworkx,padx=20)
    worklab_cuplidx.place(x=550,y=0)
    workmnsx=tk.Button(pretestwindow_cuplid,text="-",bg='#ddccff',command=lambda:mns(cuplidworkx))
    workmnsx.place(x=600,y=0)
    workplsy=tk.Button(pretestwindow_cuplid,text="+",bg='#ddccff',command=lambda:pls(cuplidworky))
    workplsy.place(x=500,y=50)
    worklab_cuplidy=tk.Label(pretestwindow_cuplid,textvariable=cuplidworky,padx=20)
    worklab_cuplidy.place(x=550,y=50)
    workmnsy=tk.Button(pretestwindow_cuplid,text="-",bg='#ddccff',command=lambda:mns(cuplidworky))
    workmnsy.place(x=600,y=50)
    workplsz=tk.Button(pretestwindow_cuplid,text="+",bg='#ddccff',command=lambda:pls(cuplidworkz))
    workplsz.place(x=500,y=100)
    worklab_cuplidz=tk.Label(pretestwindow_cuplid,textvariable=cuplidworkz,padx=20)
    worklab_cuplidz.place(x=550,y=100)
    workmnsz=tk.Button(pretestwindow_cuplid,text="-",bg='#ddccff',command=lambda:mns(cuplidworkz))
    workmnsz.place(x=600,y=100)

def presause():
    def pls(num):
        num.set(num.get()+0.5)
        print(num.get())
    def mns(num):
        num.set(num.get()-0.5)
        print(num.get())
    pretestwindow_sause=tk.Toplevel(mainwindow)
    pretestwindow_sause.title('presause' )
    pretestwindow_sause.geometry('900x600+360+120')
    pretestwindow_sause.config(bg='#ddccff')
    btnExit=tk.Button(pretestwindow_sause,text="exit",bg='red',command=pretestwindow_sause.destroy)
    btnExit.place(x=847,y=0)
    plsx=tk.Button(pretestwindow_sause,text="+",bg='#ddccff',command=lambda:pls(sausex))
    plsx.place(x=100,y=0)
    lab_sausex=tk.Label(pretestwindow_sause,textvariable=sausex,padx=20)
    lab_sausex.place(x=150,y=0)
    mnsx=tk.Button(pretestwindow_sause,text="-",bg='#ddccff',command=lambda:mns(sausex))
    mnsx.place(x=200,y=0)
    plsy=tk.Button(pretestwindow_sause,text="+",bg='#ddccff',command=lambda:pls(sausey))
    plsy.place(x=100,y=50)
    lab_sausey=tk.Label(pretestwindow_sause,textvariable=sausey,padx=20)
    lab_sausey.place(x=150,y=50)
    mnsy=tk.Button(pretestwindow_sause,text="-",bg='#ddccff',command=lambda:mns(sausey))
    mnsy.place(x=200,y=50)
    plsz=tk.Button(pretestwindow_sause,text="+",bg='#ddccff',command=lambda:pls(sausez))
    plsz.place(x=100,y=100)
    lab_sausez=tk.Label(pretestwindow_sause,textvariable=sausez,padx=20)
    lab_sausez.place(x=150,y=100)
    mnsz=tk.Button(pretestwindow_sause,text="-",bg='#ddccff',command=lambda:mns(sausez))
    mnsz.place(x=200,y=100)

    workplsx=tk.Button(pretestwindow_sause,text="+",bg='#ddccff',command=lambda:pls(sauseworkx))
    workplsx.place(x=500,y=0)
    worklab_sausex=tk.Label(pretestwindow_sause,textvariable=sauseworkx,padx=20)
    worklab_sausex.place(x=550,y=0)
    workmnsx=tk.Button(pretestwindow_sause,text="-",bg='#ddccff',command=lambda:mns(sauseworkx))
    workmnsx.place(x=600,y=0)
    workplsy=tk.Button(pretestwindow_sause,text="+",bg='#ddccff',command=lambda:pls(sauseworky))
    workplsy.place(x=500,y=50)
    worklab_sausey=tk.Label(pretestwindow_sause,textvariable=sauseworky,padx=20)
    worklab_sausey.place(x=550,y=50)
    workmnsy=tk.Button(pretestwindow_sause,text="-",bg='#ddccff',command=lambda:mns(sauseworky))
    workmnsy.place(x=600,y=50)
    workplsz=tk.Button(pretestwindow_sause,text="+",bg='#ddccff',command=lambda:pls(sauseworkz))
    workplsz.place(x=500,y=100)
    worklab_sausez=tk.Label(pretestwindow_sause,textvariable=sauseworkz,padx=20)
    worklab_sausez.place(x=550,y=100)
    workmnsz=tk.Button(pretestwindow_sause,text="-",bg='#ddccff',command=lambda:mns(sauseworkz))
    workmnsz.place(x=600,y=100)
def presauselid():
    def pls(num):
        num.set(num.get()+0.5)
        print(num.get())
    def mns(num):
        num.set(num.get()-0.5)
        print(num.get())
    pretestwindow_sauselid=tk.Toplevel(mainwindow)
    pretestwindow_sauselid.title('presauselid' )
    pretestwindow_sauselid.geometry('900x600+360+120')
    pretestwindow_sauselid.config(bg='#ddccff')
    btnExit=tk.Button(pretestwindow_sauselid,text="exit",bg='red',command=pretestwindow_sauselid.destroy)
    btnExit.place(x=847,y=0)
    plsx=tk.Button(pretestwindow_sauselid,text="+",bg='#ddccff',command=lambda:pls(sauselidx))
    plsx.place(x=100,y=0)
    lab_sauselidx=tk.Label(pretestwindow_sauselid,textvariable=sauselidx,padx=20)
    lab_sauselidx.place(x=150,y=0)
    mnsx=tk.Button(pretestwindow_sauselid,text="-",bg='#ddccff',command=lambda:mns(sauselidx))
    mnsx.place(x=200,y=0)
    plsy=tk.Button(pretestwindow_sauselid,text="+",bg='#ddccff',command=lambda:pls(sauselidy))
    plsy.place(x=100,y=50)
    lab_sauselidy=tk.Label(pretestwindow_sauselid,textvariable=sauselidy,padx=20)
    lab_sauselidy.place(x=150,y=50)
    mnsy=tk.Button(pretestwindow_sauselid,text="-",bg='#ddccff',command=lambda:mns(sauselidy))
    mnsy.place(x=200,y=50)
    plsz=tk.Button(pretestwindow_sauselid,text="+",bg='#ddccff',command=lambda:pls(sauselidz))
    plsz.place(x=100,y=100)
    lab_sauselidz=tk.Label(pretestwindow_sauselid,textvariable=sauselidz,padx=20)
    lab_sauselidz.place(x=150,y=100)
    mnsz=tk.Button(pretestwindow_sauselid,text="-",bg='#ddccff',command=lambda:mns(sauselidz))
    mnsz.place(x=200,y=100)

    workplsx=tk.Button(pretestwindow_sauselid,text="+",bg='#ddccff',command=lambda:pls(sauselidworkx))
    workplsx.place(x=500,y=0)
    worklab_sauselidx=tk.Label(pretestwindow_sauselid,textvariable=sauselidworkx,padx=20)
    worklab_sauselidx.place(x=550,y=0)
    workmnsx=tk.Button(pretestwindow_sauselid,text="-",bg='#ddccff',command=lambda:mns(sauselidworkx))
    workmnsx.place(x=600,y=0)
    workplsy=tk.Button(pretestwindow_sauselid,text="+",bg='#ddccff',command=lambda:pls(sauselidworky))
    workplsy.place(x=500,y=50)
    worklab_sauselidy=tk.Label(pretestwindow_sauselid,textvariable=sauselidworky,padx=20)
    worklab_sauselidy.place(x=550,y=50)
    workmnsy=tk.Button(pretestwindow_sauselid,text="-",bg='#ddccff',command=lambda:mns(sauselidworky))
    workmnsy.place(x=600,y=50)
    workplsz=tk.Button(pretestwindow_sauselid,text="+",bg='#ddccff',command=lambda:pls(sauselidworkz))
    workplsz.place(x=500,y=100)
    worklab_sauselidz=tk.Label(pretestwindow_sauselid,textvariable=sauselidworkz,padx=20)
    worklab_sauselidz.place(x=550,y=100)
    workmnsz=tk.Button(pretestwindow_sauselid,text="-",bg='#ddccff',command=lambda:mns(sauselidworkz))
    workmnsz.place(x=600,y=100)

btncup=tk.Button(mainwindow,text='cup',bg='#ddccff',font=('標楷體',20),command=precup)
btncup.place(x=80,y=500)
btncup_lid=tk.Button(mainwindow,text='cup_lid',bg='#ddccff',font=('標楷體',20),command=precuplid)
btncup_lid.place(x=300,y=500)
btnsause=tk.Button(mainwindow,text='sause',bg='#ddccff',font=('標楷體',20),command=presause)
btnsause.place(x=900,y=500)
btnsause_lid=tk.Button(mainwindow,text='sause_lid',bg='#ddccff',font=('標楷體',20),command=presauselid)
btnsause_lid.place(x=1020,y=500)
def getorder():
    mainwindow.mainloop()
if __name__ == "__main__":
    getorder()
    # mainwindow.mainloop()
    # # pretestwindow_cup.destroy()
    # # pretestwindow_cuplid.destroy()
    # # pretestwindow_sause.destroy()
    # # pretestwindow_sauselid.destroy()
    # mainwindow.mainloop()
    print(' ')
